version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3888:80"  # Exponer el puerto 8080 en tu máquina para acceder a la web
    container_name: cetilabs

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.43.25.0/28